apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: istio-operator
spec:
  profile: default
  tag: 1.7.0
  meshConfig:
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  addonComponents:
    istiocoredns:
      enabled: true
  components:
    pilot:
      k8s:
        env:
          - name: PILOT_CERT_PROVIDER
            value: "kubernetes"
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        env:
          - name: ISTIO_META_ROUTER_MODE
            value: "sni-dnat"
          - name: PILOT_CERT_PROVIDER
            value: "kubernetes"
        service:
          ports:
            - port: 80
              targetPort: 8080
              name: http2
              nodePort: 31708
            - port: 443
              targetPort: 8443
              name: https
              nodePort: 30017
            - port: 15443
              targetPort: 15443
              name: tls
              nodePort: 32001
  values:
    prometheus:
      enabled: false
    gateways:
      istio-ingressgateway:
        type: LoadBalancer
    kiali:
      dashboard:
        auth:
          strategy: "anonymous"
      createDemoSecret: true
    global:
      jwtPolicy: first-party-jwt
      pilotCertProvider: kubernetes
      controlPlaneSecurityEnabled: true
      podDNSSearchNamespaces:
      - global
      istiod:
        enableAnalysis: true
