apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutate-me
  namespace: demo-mutate
  labels:
    app: mutate-me
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: mutate-me
  template:
    metadata:
      labels:
        app: mutate-me
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']