apiVersion: v1
kind: Service
metadata:
  name: mutate-example
  namespace: demo-mutate
  labels:
    app: mutate-example
spec:
  ports:
    - port: 443
      name: http
  selector:
    app: mutate-example