name: create-ephemeral-track
description: 'Create an ephemeral track'
inputs:
  track-name:  # id of input
    description: 'Track name to be pushed. It must correspond with its folder name'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        cp -r pipeline-test ${{ inputs.track-name }}
        cd ${{ inputs.track-name }}
        sed 's/^\(\s*slug\s*:\s*\).*/\1${{ inputs.track-name }}/' track.yml > track.yaml.TMP
        mv track.yaml.TMP track.yaml
        cat track.yaml
      shell: bash
