name: create-ephemeral-track
description: 'Create an ephemeral track'
inputs:
  track-name:  # id of input
    description: 'Track name to be cloned. It must correspond with its folder name'
    required: true
  ephemeral-track-name:
    description: 'Ephemeral track name to be pushed'
    required: true
  token:
    description: 'Instruqt token'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ inputs.track-name }}

        # Replace slug
        sed 's/^\(\s*slug\s*:\s*\).*/\1 ${{ inputs.ephemeral-track-name }}/' track.yml > track.yml.TMP
        mv track.yml.TMP track.yml

        # Replace title
        sed 's/^\(\s*title\s*:\s*\).*/\1 ${{ inputs.ephemeral-track-name }}/' track.yml > track.yml.TMP
        mv track.yml.TMP track.yml

        # Remove all ids
        sed '/id:/d' track.yml > track.yml.TMP
        mv track.yml.TMP track.yml

        # Remove checksum
        sed '/checksum:/d' track.yml > track.yml.TMP
        mv track.yml.TMP track.yml

        # Push ephemeral track
        instruqt track push
      env:
          INSTRUQT_TOKEN: ${{ inputs.token }}
      shell: bash
