apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: example-istio-operator
  namespace: istio-operator
spec:
  addonComponents:
    grafana:
      enabled: true
    istiocoredns:
      enabled: false
    kiali:
      enabled: true
    prometheus:
      enabled: true
    tracing:
      enabled: true
  components:
    citadel:
      enabled: false
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
  

  profile: default
  tag: 1.6.4
  values:
    gateways:
      istio-ingressgateway:
        k8sIngress: true
        k8sIngressHttps: true
        autoscaleEnabled: false
        type: NodePort
        debug: info
        #domain: ${CLUSTER_DOMAIN}
        tolerations:
          - effect: "NoSchedule"
            key: "node-role.kubernetes.io/master"
            operator: "Equal"
        nodeSelector:
          ingress-ready: "true"

    global:
      mtls:
        enabled: true 
      jwtPolicy: first-party-jwt 
      pilotCertProvider: kubernetes
      #proxy:
      #  clusterDomain: ${CLUSTER_DOMAIN}
      #trustDomain: ${CLUSTER_DOMAIN}
    kiali:
      enabled: true
      replicaCount: 1
      dashboard:
        auth:
          strategy: "anonymous"
      createDemoSecret: true

