name: pipeline-test
env:
  track-name: pipeline-test
on:
  workflow_dispatch: # Manual trigger
    inputs:
      also-deploy:
        description: 'Run test and deploy if this attribute is true'     
        required: true
        default: 'false'
jobs:
  prepare:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: echo test