name: pipeline-test
env:
  track-name: pipeline-test
on:
  workflow_dispatch: # Manual trigger
    inputs:
      also-deploy:
        description: 'Run test and deploy if this attribute is true'     
        required: true
        default: 'false'
  push:
    # branches:
    #   - main
  # pull_request:
  #   branches:
  #     - main
  # schedule:  # This runs every night at 12am
  #   - cron:  '0 0 * * *'
jobs:
  prepare:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/download-cli
      - uses: actions/upload-artifact@v2
        with:
          name: instruqt-cli
          path: instruqt
  build:
    needs: [prepare]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: instruqt-cli
          path: /usr/local/bin
      - uses: ./.github/actions/create-ephemeral-track
        with:
          track-name: ci-${{ github.ref }}
      - uses: ./.github/actions/push-track
        with:
          track-name: ci-${{ github.ref }}
