name: test-workflow
on:
  workflow_dispatch: # Manual trigger
    inputs:
      also-deploy:
        description: 'Run test and deploy if this attribute is true'     
        required: true
        default: 'false'
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  # schedule:  # This runs every night at 12am
  #   - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: echo test
  